#!/bin/bash
# Calls nitrogen to randomly select a new wallpaper every
# xx minutes without the need for GUI. Time written in seconds.
# Written for i3wm by Baphomet, Junius XXX, MMXIX

while true
do
	nitrogen --random --set-zoom-fill /home/caddy.ssd/Pictures/Wallpapers/
	sleep 900
done
